/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import entity.BankAccount;
import entity.Card;
import entity.Customer;
import org.junit.Test;

import java.math.BigDecimal;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

        BankAccount bankAccount = new BankAccount();
        bankAccount.setAccount("968574123");
        bankAccount.setDeposit(new BigDecimal(100000.000000));
        bankAccount.setCredit(new BigDecimal(0.000000));

        Card card = new Card();
        card.setNumber("1234 5678 9101 1121");
        card.setBankAccount(bankAccount);

        Customer customer = new Customer();
        customer.setName("Vasja");
        customer.setSurname("Pjatochkin");
        customer.setCard(card);










    }
}
